export { default as Home } from './Home';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
// export { default as ChangePassword } from "./ChangePassword";
export { default as Collections } from './Collections';
export { default as MyOrder } from './MyOrder';
export { default as MyProfile } from './MyProfile';
export { default as PaymentDetails } from './PaymentDetails';
export { default as ProductDetails } from './ProductDetails';
export { default as ProductReviews } from './ProductReviews';
export { default as Review } from './Review';
// export { default as SavedAddress } from "./SavedAddress";
export { default as Shipping } from './Shipping';
export { default as ShoppingBag } from './ShoppingBag';
export { default as Wishlist } from './Wishlist';
